// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOf0kZaZ02-UZ7TUYVNCGN8Ekn_MgkvsM',
    appId: '1:869040424342:web:f83e6029173187820649b7',
    messagingSenderId: '869040424342',
    projectId: 'resumefunctionality',
    authDomain: 'resumefunctionality.firebaseapp.com',
    storageBucket: 'resumefunctionality.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUVwnBy2jWvMu_GB_gL2LNmEJKTKQJxUA',
    appId: '1:869040424342:android:e590124bf2fcd30a0649b7',
    messagingSenderId: '869040424342',
    projectId: 'resumefunctionality',
    storageBucket: 'resumefunctionality.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhD7h0KqlXaR3LjUIOEDlbHtLDGxEVOC4',
    appId: '1:869040424342:ios:14e3841ddc52959c0649b7',
    messagingSenderId: '869040424342',
    projectId: 'resumefunctionality',
    storageBucket: 'resumefunctionality.appspot.com',
    iosBundleId: 'com.example.newResumeFmaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhD7h0KqlXaR3LjUIOEDlbHtLDGxEVOC4',
    appId: '1:869040424342:ios:14e3841ddc52959c0649b7',
    messagingSenderId: '869040424342',
    projectId: 'resumefunctionality',
    storageBucket: 'resumefunctionality.appspot.com',
    iosBundleId: 'com.example.newResumeFmaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOf0kZaZ02-UZ7TUYVNCGN8Ekn_MgkvsM',
    appId: '1:869040424342:web:60dd6449d7ad81d40649b7',
    messagingSenderId: '869040424342',
    projectId: 'resumefunctionality',
    authDomain: 'resumefunctionality.firebaseapp.com',
    storageBucket: 'resumefunctionality.appspot.com',
  );
}
